# Generated by Django 5.1.1 on 2025-08-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_token',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='face_image',
            field=models.ImageField(default='media/vinoth.jpeg', upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='qr_token',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_qr',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='qr_code',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
